/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cronosfmt;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author roberto.salinas
 */
public class frameCronosFmt extends javax.swing.JFrame {

    /**
     * Creates new form frameCronosFmt
     */
    public frameCronosFmt() {
        initComponents();
        dpFechaDesde.setDate(new Date());
        dpFechaHasta.setDate(new Date());        
    }

    public void fillPersonas(){
    // para despues
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonGenRep = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        cboxLegajos = new javax.swing.JComboBox<>();
        dpFechaDesde = new org.jdesktop.swingx.JXDatePicker();
        dpFechaHasta = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setDisplayedMnemonic('E');
        jLabel1.setText("Elija Persona");

        jLabel2.setText("Fecha Desde:");

        jLabel3.setText("Fecha Hasta:");

        botonGenRep.setText("Generar Reporte");
        botonGenRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenRepActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        cboxLegajos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboxLegajos.setEditor(null);
        cboxLegajos.setName("legajoSelect"); // NOI18N

        dpFechaDesde.setToolTipText("Fecha Desde");
        dpFechaDesde.setName("fecDesde"); // NOI18N

        dpFechaHasta.setName("fecHasta"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonGenRep)
                                    .addComponent(dpFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dpFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 78, Short.MAX_VALUE))
                            .addComponent(cboxLegajos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboxLegajos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dpFechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dpFechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonGenRep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonGenRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenRepActionPerformed
    Persona p = null;
    // levanto las fichadas de la persona seleccionada entre las fechas seleccionadas y las agrego a la persona
    try{   
        sentencia=conexion.createStatement(
            ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);  
        SimpleDateFormat sFeFor = new SimpleDateFormat("yyyyMMdd");
        String sLegajo = (String) cboxLegajos.getSelectedItem();
        sLegajo = sLegajo.substring(0,sLegajo.indexOf(" "));
        // ubico a la persona        
        for (int i = 1;i <= listaPersonas.size();i++){
             p = listaPersonas.get(i);             
             if (sLegajo.equals(p.getLegajo())){
                 break;
             }             
        }            
        String sFichada = "select * from fichadas where fichada_numero = " 
                + sLegajo + " and fichada_fecha >= " + sFeFor.format(dpFechaDesde.getDate()) 
                + " and fichada_fecha <= " + sFeFor.format(dpFechaHasta.getDate());
        ResultSet rs = sentencia.executeQuery(sFichada);           
        while(rs.next()){
           sFichada = rs.getString("fichada_fecha") + " " + rs.getString("fichada_hora") + " " + rs.getString("fichada_numero") + " " + rs.getString("fichada_evento");           
           JOptionPane.showMessageDialog(null,sFichada);
            // agrego a lista de fichadas
            Fichada f = new Fichada();
            f.setDia(LocalDate.now());

            p.addFichada(f);                        
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error al ejecutar query "+e);
            return ;
        }   
    try{
    // comienzo a armar el reporte
        JasperReport reporte = (JasperReport) JRLoader.loadObject("horasPorPersona.jasper");
        // armo el seudodatasource
        fichadasDataSource dsFichadas = new fichadasDataSource();
        dsFichadas.setPersona(p);
        JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, dsFichadas);
        JRExporter exporter = new JRPdfExporter(); 
        exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
        exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reporte2PDF_2.pdf")); 
        exporter.exportReport();        
        }
        catch (JRException e){
        JOptionPane.showMessageDialog(null,"Error en jasper "+e);
        }   
    }//GEN-LAST:event_botonGenRepActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCronosFmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCronosFmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCronosFmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCronosFmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCronosFmt().setVisible(true);
            }
        });
    }
    Connection conexion;
    private ArrayList<Persona> listaPersonas;

    public void setListaPersonas(ArrayList<Persona> listaPersonas) {
        this.listaPersonas = listaPersonas;
    }
    java.sql.Statement sentencia; 
    String sFichada;

    public void setConexion(Connection conexion) {
        this.conexion = conexion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGenRep;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> cboxLegajos;
    private org.jdesktop.swingx.JXDatePicker dpFechaDesde;
    private org.jdesktop.swingx.JXDatePicker dpFechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables


    public void addCboxLegajos(String sItem) {
       this.cboxLegajos.addItem(sItem);
    }
    
    public void removeCboxLegajos() {
        this.cboxLegajos.removeAllItems();
    }

}
